package com.omar.blog_agent.model;

import java.util.List;

/**
 * SEO and metadata fields generated by the LLM for a finished post,
 * rendered into the YAML front matter block by
 * {@link com.omar.blog_agent.agent.BlogWriterAgent#addFrontMatter}.
 *
 * @param description a 1-2 sentence summary suitable for meta descriptions
 * @param tags        category tags for the post
 * @param keywords    SEO keywords, capped by
 *                    {@link com.omar.blog_agent.config.BlogAgentProperties#numberOfKeywords()}
 * @param readTime    a human-readable estimate (e.g. {@code "4 min read"}) produced
 *                    by {@link com.omar.blog_agent.tool.ReadingStatsTool}
 */
public record FrontMatter(String description, List<String> tags, List<String> keywords, String readTime) {
}
