package com.omar.blog_agent.model;

/**
 * Promotional snippets for sharing a published post, generated by
 * {@link com.omar.blog_agent.agent.PromotionAgent#generateSocialPosts}.
 *
 * @param twitterPost  a short, punchy post sized for X/Twitter, including a
 *                     hook and an implicit call to read more
 * @param linkedInPost a longer, more professional post suited to LinkedIn's
 *                     audience and format
 */
public record SocialPosts(String twitterPost, String linkedInPost) {
}
