package com.omar.blog_agent.model;

/**
 * An image-generation prompt and accessibility alt text for the post's hero
 * image, generated by
 * {@link com.omar.blog_agent.agent.PromotionAgent#generateThumbnailPrompt}.
 *
 * <p>{@code imagePrompt} is written to be pasted directly into an
 * image-generation tool (Midjourney, DALL-E, etc.); this project does not
 * call one itself.</p>
 *
 * @param imagePrompt a detailed visual description suitable for an image generator
 * @param altText     concise accessibility alt text describing the intended image
 */
public record ThumbnailPrompt(String imagePrompt, String altText) {
}
